### ISSUE TITLE
Add syntax for image size

### ISSUE THREAD

**Issue by n-studio** [larsch/creole#1]
I think we should add support for:
{{image.jpg?50x100}}
{{image.jpg?50%|alternate text}}

With regex looking like this:
/\A{{\s_(._?)(\?(\d+x\d+|\d+%))?\s_(|\s_(._?)\s_)?}}/

I can't make a PR right now, maybe next month.

**Comment by minad** [comment]
You can already achieve that by overwriting `make_image`. I think it is better to only support the plain creole standard.
